apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: git-local
build:
  artifacts:
    - image: adservice
      context: src/adservice
      docker:
        dockerfile: Dockerfile
    - image: cartservice
      context: src/cartservice/src
      docker:
        dockerfile: Dockerfile
    - image: checkoutservice
      context: src/checkoutservice
      docker:
        dockerfile: Dockerfile
    - image: currencyservice
      context: src/currencyservice
      docker:
        dockerfile: Dockerfile
    - image: emailservice
      context: src/emailservice
      docker:
        dockerfile: Dockerfile
    - image: frontend
      context: src/frontend
      docker:
        dockerfile: Dockerfile
    - image: loadgenerator
      context: src/loadgenerator
      docker:
        dockerfile: Dockerfile
    - image: paymentservice
      context: src/paymentservice
      docker:
        dockerfile: Dockerfile
    - image: productcatalogservice
      context: src/productcatalogservice
      docker:
        dockerfile: Dockerfile
    - image: recommendationservice
      context: src/recommendationservice
      docker:
        dockerfile: Dockerfile
    - image: shippingservice
      context: src/shippingservice
      docker:
        dockerfile: Dockerfile
    - image: shoppingassistantservice
      context: src/shoppingassistantservice
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - kubernetes-manifests/*.yaml 
    
