apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: git-local
build:
  artifacts:
    - image: adservice
      context: src/adservice
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: busybox
      context: src/cartservice/src
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: cartservice
      context: src/cartservice/tests
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: checkoutservice
      context: src/checkoutservice
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: currencyservice
      context: src/currencyservice
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: emailservice
      context: src/frontend
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: frontend
      context: src/paymentservice
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: ghcr.io/micheal-91/adservice
      context: src/productcatalogservice
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: ghcr.io/micheal-91/cartservice
      context: src/shippingservice
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: ghcr.io/micheal-91/checkoutservice
      context: src/adservice
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/micheal-91/currencyservice
      context: src/cartservice/src
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/micheal-91/emailservice
      context: src/cartservice/src
      docker:
        dockerfile: Dockerfile.debug
    - image: ghcr.io/micheal-91/frontend
      context: src/checkoutservice
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/micheal-91/paymentservice
      context: src/currencyservice
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/micheal-91/productcatalogservice
      context: src/emailservice
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/micheal-91/recommendationservice
      context: src/frontend
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/micheal-91/shippingservice
      context: src/loadgenerator
      docker:
        dockerfile: Dockerfile
    - image: loadgenerator
      context: src/paymentservice
      docker:
        dockerfile: Dockerfile
    - image: paymentservice
      context: src/productcatalogservice
      docker:
        dockerfile: Dockerfile
    - image: productcatalogservice
      context: src/recommendationservice
      docker:
        dockerfile: Dockerfile
    - image: recommendationservice
      context: src/shippingservice
      docker:
        dockerfile: Dockerfile
    - image: redis
      context: src/shoppingassistantservice
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - kubernetes-manifests
deploy:
  helm:
    releases:
      - name: onlineboutique
        chartPath: helm-chart
        valuesFiles:
          - helm-chart/values.yaml
        version: 0.10.5
profiles:
  - name: kustomize
    manifests:
      kustomize:
        paths:
          - kustomize
  - name: base
    manifests:
      kustomize:
        paths:
          - kustomize/base
  - name: alloydb
    manifests:
      kustomize:
        paths:
          - kustomize/components/alloydb
  - name: container-images-registry
    manifests:
      kustomize:
        paths:
          - kustomize/components/container-images-registry
  - name: container-images-tag
    manifests:
      kustomize:
        paths:
          - kustomize/components/container-images-tag
  - name: container-images-tag-suffix
    manifests:
      kustomize:
        paths:
          - kustomize/components/container-images-tag-suffix
  - name: custom-base-url
    manifests:
      kustomize:
        paths:
          - kustomize/components/custom-base-url
  - name: cymbal-branding
    manifests:
      kustomize:
        paths:
          - kustomize/components/cymbal-branding
  - name: google-cloud-operations
    manifests:
      kustomize:
        paths:
          - kustomize/components/google-cloud-operations
  - name: memorystore
    manifests:
      kustomize:
        paths:
          - kustomize/components/memorystore
  - name: network-policies
    manifests:
      kustomize:
        paths:
          - kustomize/components/network-policies
  - name: non-public-frontend
    manifests:
      kustomize:
        paths:
          - kustomize/components/non-public-frontend
  - name: service-mesh-istio
    manifests:
      kustomize:
        paths:
          - kustomize/components/service-mesh-istio
  - name: shopping-assistant
    manifests:
      kustomize:
        paths:
          - kustomize/components/shopping-assistant
  - name: single-shared-session
    manifests:
      kustomize:
        paths:
          - kustomize/components/single-shared-session
  - name: spanner
    manifests:
      kustomize:
        paths:
          - kustomize/components/spanner
  - name: without-loadgenerator
    manifests:
      kustomize:
        paths:
          - kustomize/components/without-loadgenerator
  - name: memorystore-with-all-components
    manifests:
      kustomize:
        paths:
          - kustomize/tests/memorystore-with-all-components
  - name: service-mesh-istio-with-all-components
    manifests:
      kustomize:
        paths:
          - kustomize/tests/service-mesh-istio-with-all-components
  - name: spanner-with-all-components
    manifests:
      kustomize:
        paths:
          - kustomize/tests/spanner-with-all-components
