apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/micheal-91/microservices-demo.git'
    targetRevision: HEAD
    path: .                    # Tells ArgoCD to look in the root folder of your repo
    directory:
      include: 'test-hydrated.yaml' # Directly syncs your exact Skaffold output file
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default         # Deploys your microservices into the default namespace
  syncPolicy:
    automated:
      prune: true              # Automatically deletes old resources if you remove them from YAML
      selfHeal: true           # Automatically fixes configuration drift if someone modifies RKE2 manually
